src/Entity/Person.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Table(name="person")
 * @ORM\Entity(repositoryClass="App\Repository\PersonRepository")
 * @UniqueEntity(fields="email", message="Email already taken")
 * @UniqueEntity(fields="username", message="Username already taken")
 */
class Person implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=55)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=55)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\Email()
     * @Assert\NotBlank()
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank()
     */
    private $phonenumber;

    /**
     * @Assert\Length(
     *      min = 2,
     *      max = 8,
     *      minMessage = "Le mot de passe doit contenir au mininum {{ limit }} caractères",
     *      minMessage = "Le mot de passe doit contenir au maximum {{ limit }} caractères",
     * )
     * @Assert\NotBlank()
     */
    private $plainpassword;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(name="roles", type="json")
     */
    private $roles = array("ROLE_USER");

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime
     */
    private $passwordRequestedAt;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    public function __construct()
    {
        $this->isActive = true;
        $this->roles = ['ROLE_USER'];
        $this->ads = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhonenumber(): ?string
    {
        return $this->phonenumber;
    }

    public function setPhonenumber(string $phonenumber): self
    {
        $this->phonenumber = $phonenumber;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    function getPlainPassword() {
        return $this->plainpassword;
    }

    function setPlainPassword($plainpassword) {
        $this->plainpassword = $plainpassword;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getRoles()
    {
        return $this->roles;
    }

    public function setRoles(array $roles)
    {
        if (!in_array('ROLE_USER', $roles))
        {
            $roles[] = 'ROLE_USER';
        }
        foreach ($roles as $role)
        {
            if(substr($role, 0, 5) !== 'ROLE_') {
                throw new InvalidArgumentException("Chaque rôle doit commencer par 'ROLE_'");
            }
        }
        $this->roles = $roles;
        return $this;
    }


    function addRole($role) {
        $this->roles[] = $role;
    }

    public function eraseCredentials()
    {
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    function setIsActive($isActive) {
        $this->isActive = $isActive;

        return $this;
    }

    function getIsActive(){

        return $this->isActive;
    }

    public function getPasswordRequestedAt()
    {
        return $this->passwordRequestedAt;
    }


    public function setPasswordRequestedAt($passwordRequestedAt)
    {
        $this->passwordRequestedAt = $passwordRequestedAt;
        return $this;
    }

    public function getToken()
    {
        return $this->token;
    }

    public function setToken($token)
    {
        $this->token = $token;
        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>
        {% block title %}
            {% if title is defined %}{{title}}{% else %}Title{% endif %} | Nom du site
        {% endblock %}
    </title>
    {% block stylesheets %}
        {# bootstrap #}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
        {# custom #}
        <link rel="stylesheet" href="/css/styles.css">
        {#<link rel="stylesheet" href="/css/drag_n_drop.css">#}
    {% endblock %}
    <link rel="icon" type="image/x-icon" href="" />
</head>

<body id="{% block body_id %}{% endblock %}">

{% block header %}
    <header id="header" class="bck1 border-bottom align-middle">
        <div class="container ">
            <div class="row">
            <div class="col-10">
                <div class="ml-5 pl-5">
                    <h1>{% if title is defined %}{{title}}{% else %}Header{% endif %}</h1>
                    <h3>{% if title2 is defined %}{{title2}}{% endif %}</h3>
                </div>
            </div>
                {% if is_granted('ROLE_USER') %}
                <div class="col-2">
                    <div><br>
                        <a class="btn btn-outline-warning text-right" href="{{path('logout')}}">Déconnexion</a>
                    </div>
                {% endif %}
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block nav %}
    <nav id="main-nav" class="container navbar navbar-expand-lg navbar-light bg-light border rounded mb-3">
        <ul class="navbar-nav">
            <li class="nav-item {% if mainNavHome is defined %}active{% endif %}">
                <a class="nav-link" href="{{path('homepage')}}">Accueil</a>
            </li>
            {% if is_granted('ROLE_USER') %}
                <li class="nav-item {% if mainNavMember is defined %}active{% endif %}">
                    <a class="nav-link" href="{{path('account')}}">Espace membre</a>
                </li>
            {% endif %}
            {% if is_granted('ROLE_ADMIN') %}
                <li class="nav-item {% if mainNavAdmin is defined %}active{% endif %}">
                    <a class="nav-link" href="{{path('admin')}}">Espace admin</a>
                </li>
            {% endif %}
            {% if is_granted('ROLE_USER') %}
                <li class="nav-item {% if mainNavMember is defined %}active{% endif %}">
                    <a class="nav-link" href="{{path('ad_new')}}">Déposer une annonce</a>
                </li>
            {% endif %}
            {% if is_granted('ROLE_USER') %}
                <li class="nav-item {% if mainNavMember is defined %}active{% endif %}">
                    <a class="nav-link" href="{{path('mes_annonces')}}">Mes annonces</a>
                </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if is_granted('ROLE_USER') %}
                <li class="input-group">
                    <form action="{{ path('search') }}" method="post">
                        <input class="form-control py-2 border-right-0 border text-right" type="search" name="search" placeholder="&#xF002;" style="font-family:Arial, FontAwesome">
                    </form>
                    <a class="nav-link text-center" href="{{path('vue_recherche_avancee')}}">Recherche Avancée</a>
                </li>
            {% else %}
                <li class="nav-item {% if mainNavLogin is defined %}active{% endif %}">
                    <a class="nav-link" href="{{path('login')}}">Connexion</a>
                </li>
                <li class="nav-item {% if mainNavRegistration is defined %}active{% endif %}">
                    <a class="nav-link" href="{{path('registration')}}">Inscription</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}


{% block search %}
{% endblock %}

{% block flash %}
    {% for flash_message in app.session.flashbag.get('success') %}
        <div class="container alert alert-success" role="alert">
            {{ flash_message }}
        </div>
    {% endfor %}
    {% for flash_message in app.session.flashbag.get('info') %}
        <div class="container alert alert-info" role="alert">
            {{ flash_message }}
        </div>
    {% endfor %}
    {% for flash_message in app.session.flashbag.get('warning') %}
        <div class="container alert alert-warning" role="alert">
            {{ flash_message }}
        </div>
    {% endfor %}
    {% for flash_message in app.session.flashbag.get('danger') %}
        <div class="container alert alert-danger" role="alert">
            {{ flash_message }}
        </div>
    {% endfor %}
{% endblock %}

<div class="container bck1 padded">
    {% block body %}
    {% endblock %}
</div>

{% block footer %}
    <footer id="footer" class="bck1 border-top">
        <div class="container">
            <h4>Footer</h4>
        </div>
    </footer>
{% endblock %}

{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <script src="/js/main.js"></script>
    {#<script src="/js/drag_n_drop.js"></script>#}
{% endblock %}
</body>
</html>

templates/form.html.twig
{% block body %}

{{ form_start(form) }}
<div class="grid-container">
    <div class="grid-x grid-padding-x">
        <div class="small-12 medium-6 medium-offset-3 large-4 large-offset-4 cell">
            {{ form_row(form.username) }}
        </div>
        <div class="small-12 medium-6 medium-offset-3 large-4 large-offset-4 cell">
            {{ form_row(form.firstname) }}
        </div>
        <div class="small-12 medium-6 medium-offset-3 large-4 large-offset-4 cell">
            {{ form_row(form.lastname) }}
        </div>
        <div class="small-12 medium-6 medium-offset-3 large-4 large-offset-4 cell">
            {{ form_row(form.email) }}
        </div>
        <div class="small-12 medium-6 medium-offset-3 large-4 large-offset-4 cell">
            {{ form_row(form.phonenumber) }}
        </div>
        <div class="small-12 medium-6 medium-offset-3 large-4 large-offset-4 cell">
            {{ form_row(form.plainPassword.first) }}
        </div>
        <div class="small-12 medium-6 medium-offset-3 large-4 large-offset-4 cell">
            {{ form_row(form.plainPassword.second) }}
        </div>
    </div>
</div>
<br>
{{ form_end(form) }}
{% endblock %}

templates/form_ad_creation.html.twig
{% block body %}

{{ form_start(form) }}
    {{ form_row(form.category) }}
    {{ form_row(form.title) }}
    {{ form_row(form.description) }}

    <div class="d-flex justify-content-between">
        {{ form_row(form.creation_date) }}
        {{ form_row(form.price) }}
        {{ form_row(form.country) }}
    </div>

    {{ form_row(form.photo) }}
{{ form_end(form) }}
    <div>
        <a href="{{ path('mes_annonces') }}" class="btn btn-secondary btn-block">Annuler</a>
    </div>
    <br>
{% endblock %}